receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64

  batch:

  transform/logs:
    log_statements:
      - context: log
        statements:
          - set(attributes["level"], ConvertCase(severity_text, "lower"))

exporters:
  otlphttp/victoriametrics:
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/v1/metrics
    compression: gzip
    encoding: proto

  otlphttp/victorialogs:
    logs_endpoint: http://victorialogs:9428/insert/opentelemetry/v1/logs
    compression: gzip
    encoding: proto

service:
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - batch
      exporters:
        - otlphttp/victoriametrics

    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - transform/logs
        - batch
      exporters:
        - otlphttp/victorialogs

