create schema if not exists auth;

create table auth.roles
(
    id uuid primary key,
    name text null,
    normalized_name text null,
    concurrency_stamp text null
);

create unique index ux_roles_normalized_name
    on auth.roles (normalized_name)
    where normalized_name is not null;

create table auth.users
(
    id uuid primary key,
    user_name text not null,
    normalized_user_name text not null,
    email text not null,
    normalized_email text not null,
    email_confirmed boolean not null,
    password_hash text null,
    security_stamp text null,
    concurrency_stamp text null,
    phone_number text null,
    phone_number_confirmed boolean not null,
    two_factor_enabled boolean not null,
    lockout_end timestamptz null,
    lockout_enabled boolean not null,
    access_failed_count integer not null,
    created_at timestamptz not null,
    last_login_at timestamptz null,
    user_name_changed_at timestamptz null
);

create unique index ux_users_normalized_user_name
    on auth.users (normalized_user_name)
    where normalized_user_name is not null;

create unique index ux_users_normalized_email
    on auth.users (normalized_email);

create table auth.role_claims
(
    id integer generated by default as identity primary key,
    role_id uuid not null,
    claim_type text null,
    claim_value text null,
    constraint fk_auth_role_claims_roles_role_id
        foreign key (role_id)
        references auth.roles (id)
        on delete cascade
);

create index ix_auth_role_claims_role_id
    on auth.role_claims (role_id);

create table auth.user_roles
(
    user_id uuid not null,
    role_id uuid not null,
    constraint pk_auth_user_roles primary key (user_id, role_id),
    constraint fk_auth_user_roles_users_user_id
        foreign key (user_id)
        references auth.users (id)
        on delete cascade,
    constraint fk_auth_user_roles_roles_role_id
        foreign key (role_id)
        references auth.roles (id)
        on delete cascade
);

create index ix_auth_user_roles_role_id
    on auth.user_roles (role_id);

create table auth.user_claims
(
    id integer generated by default as identity primary key,
    user_id uuid not null,
    claim_type text null,
    claim_value text null,
    constraint fk_auth_user_claims_users_user_id
        foreign key (user_id)
        references auth.users (id)
        on delete cascade
);

create index ix_auth_user_claims_user_id
    on auth.user_claims (user_id);

create table auth.user_logins
(
    login_provider text not null,
    provider_key text not null,
    provider_display_name text null,
    user_id uuid not null,
    constraint pk_auth_user_logins primary key (login_provider, provider_key),
    constraint fk_auth_user_logins_users_user_id
        foreign key (user_id)
        references auth.users (id)
        on delete cascade
);

create index ix_auth_user_logins_user_id
    on auth.user_logins (user_id);

create table auth.user_tokens
(
    user_id uuid not null,
    login_provider text not null,
    name text not null,
    value text null,
    constraint pk_auth_user_tokens primary key (user_id, login_provider, name),
    constraint fk_auth_user_tokens_users_user_id
        foreign key (user_id)
        references auth.users (id)
        on delete cascade
);

create table auth.otp_challenges
(
    id uuid primary key,
    email text not null,
    code_hash text not null,
    requested_by_guest_id uuid null,
    created_at timestamptz not null,
    ttl interval not null,
    consumed_at timestamptz null,
    attempt_count integer not null default 0
);

create index ix_auth_otp_challenges_email_created_at
    on auth.otp_challenges (email, created_at desc);

create table auth.otp_rate_limits
(
    email text primary key,
    window_started_at timestamptz not null,
    request_count integer not null,
    last_requested_at timestamptz not null,
    constraint ck_auth_otp_rate_limits_request_count
        check (request_count > 0)
);

create table auth.user_name_filter_versions
(
    id integer generated by default as identity primary key,
    version integer not null,
    published_at timestamptz not null,
    is_active boolean not null
);

create unique index ux_user_name_filter_versions_is_active
    on auth.user_name_filter_versions(is_active)
    where is_active;

create table auth.user_notice_views
(
    user_id uuid not null,
    notice_code text not null,
    type integer not null,
    do_not_show_again boolean,

    primary key (user_id, notice_code)
);