create schema game;

create table game.difficulties
(
    code text primary key,
    name text not null
);

create table game.game_sources
(
    id bigint generated by default as identity primary key,
    word text not null
);

create table game.versioned_game_sources
(
    game_source_id bigint not null,
    words_version integer not null,
    difficulty_code text not null,
    predicted_difficulty integer not null,

    constraint pk_versioned_game_sources
        primary key(game_source_id, words_version),

    constraint fk_versisoned_game_sources_difficulties_difficulty_code
        foreign key (difficulty_code)
        references game.difficulties (code),

    constraint fk_versisoned_game_sources_game_sources_game_source_id
        foreign key (game_source_id)
        references game.game_sources (id)
);

create table game.daily_game_source_reviews
(
    game_source_id bigint primary key,
    words_version integer not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,

    constraint fk_daily_game_source_reviews_versioned_game_sources_game_source_id_words_version
        foreign key (game_source_id, words_version)
        references game.versioned_game_sources (game_source_id, words_version)
        on delete restrict
);

create table game.approved_daily_game_sources
(
    game_source_id bigint primary key,

    constraint fk_approved_daily_game_sources_daily_game_source_reviews_game_source_id
        foreign key (game_source_id)
        references game.daily_game_source_reviews (game_source_id)
        on delete restrict
);

create table game.single_game_daily_schedule
(
    day date not null primary key,
    game_source_id bigint not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,

    constraint fk_single_game_daily_schedule_approved_daily_game_sources_game_source_id
        foreign key (game_source_id)
        references game.approved_daily_game_sources (game_source_id)
        on delete restrict
);

create table game.single_games
(
    id uuid primary key,
    game_source_id bigint not null,
    mode integer not null,
    player_id uuid not null,
    state integer not null,
    created_at timestamptz not null,
    started_at timestamptz null,
    updated_at timestamptz not null,    
    finished_at timestamptz null,
    day_of_daily_game date null,
    words_version integer not null,
    closest_guess_distance integer null,
    reveal_letter_hints_total integer not null,
    calculated_reveal_letter_hint_penalties integer[] null,
    ordered_letters_indexes_for_reveal integer[] null,
    display_word jsonb not null,
    used_hints jsonb not null,

    constraint fk_single_versioned_games_sources_game_source_id_words_version
        foreign key (game_source_id, words_version)
        references game.versioned_game_sources (game_source_id, words_version)
);

create table game.guesses
(
    id bigint generated by default as identity primary key,
    game_id uuid not null,
    word text not null,
    distance integer not null,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    source integer not null,

    constraint fk_guesses_single_games_game_id
        foreign key (game_id)
        references game.single_games (id)
        on delete cascade
);

create table game.single_game_results
(
    game_id uuid primary key,
    game_source_id bigint not null,
    mode integer not null,
    difficulty_code text not null,
    day_of_daily_game date null,
    player_id uuid not null,
    duration interval not null,
    score integer not null,
    attempts integer not null,
    reveal_halfway_word_hints_used integer not null,
    reveal_length_hint_used boolean not null,
    reveal_letter_hints_used integer not null,
    state integer not null,

    constraint fk_single_game_results_single_games_game_id
    foreign key (game_id)
    references game.single_games (id)
    on delete cascade
);

create table game.daily_game_streaks_info
(
    player_id uuid primary key,
    current_streak integer not null,
    longest_streak integer not null,
    last_success_day date not null
);

create table game.arcade_game_stats
(
    player_id uuid not null,
    difficulty_code text not null,
    guessed_games integer not null,
    total_score integer not null,
    total_attempts integer not null,
    total_duration interval not null,
    average_score numeric(11,1) not null,
    average_duration interval not null,

    constraint pk_arcade_game_stats
    primary key(player_id, difficulty_code)
)
