<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Database/Migrations/*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="ZiggyCreatures.FusionCache" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.CysharpMemoryPack" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\WordoGuessr.API.BuildingBlocks\WordoGuessr.API.BuildingBlocks.csproj" />
    <ProjectReference Include="..\WordoGuessr.Words.App\WordoGuessr.Words.App.csproj" />
  </ItemGroup>
</Project>
